source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Delta_Example', :exclusive => true do
  pod 'Delta', :path => '../'
end

target 'Delta_Tests', :exclusive => true do
  pod 'Delta', :path => '../'

  
end
